### ISSUE TITLE
Servers with secure connection required not showing up in server list

### ISSUE THREAD

**Issue by fiLLLip** [hippojay/plugin.video.plexbmc#105] opened 2015-06-04 14:31 UTC
Due to the new update with secure connection, servers with secure connection set to required no longer show up in server list.
Read this news post for more information: https://blog.plex.tv/2015/06/04/its-not-easy-being-green-secure-communication-arrives/

Once reset to secure connection preferred it shows up in list again.

**Comment by vulcanjedi** [comment] 2015-10-25 00:02
Agree would love if Secure (required) connections were supported. All the other Plex clients I believe finally support it.,as does PlexPy..So I finally made the move toe REQUIRED...cept I realized this plugin doesnt.  Would love if this enhancement request could get addressed.

**Comment by hippojay** [comment] 2015-10-25 07:05
This is something I am working on now. The issue is lack of TLS SNI support in Python 2.7 - it's less straightforward than it should be (I've added the support, but the plugin just hangs for some reason when making an ssl connection). 

I'm having to re-jig some modules to check - but might investigate plexpy to see how they have done it.

**Comment by vulcanjedi** [comment] 2015-10-25 16:55
Great thanks for the feedback Hippojay. keep up the great work. Yea PlexPy is the best new plex monitoring app, although its strangely missing new content notifications but their SSL / secure(required) connection works. Thats a great idea if you can get any inspiration on how to resolve particular since they are python based too. The two devs there seem pretty cool as well and update regularly.

**Comment by hippojay** [comment] 2015-10-27 00:24
Just been checking plexpy over and, whilst an SSL connection is made, certs are not verified unless you are running python 2.7.9.  Plex makes use of Server Name Indication in it's certs, which isn;t supported in python until 2.7.9.  The problem I have is that KODI runs an earlier version and therefore I connect perform certificate based verification.

As a workaround I can turn off the verification and get an SSL connections running - which might have to be the way if I cannot get SNI working within Kodi (or until Kodi upgrads to a newer version of python).

**Comment by ianimacleod** [comment] 2015-11-10 04:38
Very interested to see where this goes. Thanks for the updates.

**Comment by hippojay** [comment] 2015-11-13 21:20
Fix has been put into to allow SSL-only servers to be discovered (basically, try https first and fallback).  I am unable to verify the certificates though, due to some python type issues in kodi.

So encrypted: yes - verified: no.  I'll see if Jarvis brings in a slightly later version of python (I need 2.7.9 minimum) but until then we are stuck at this point

**Closed by hippojay** 2015-11-13 21:20 UTC

**Comment by fiLLLip** [comment] 2015-11-13 23:46
Great work @hippojay!

**Comment by vulcanjedi** [comment] 2015-11-14 01:17
Is this only in the Isengard fixes pull?

**Comment by hippojay** [comment] 2015-11-14 07:22
Yes. I'm putting a series of fixes together before merging them into the isengard branch. I'll then test against helix and backport into the helix branch. 

My expectation is that helix will be frozen, and new features will go into isengard.

**Comment by smurfster** [comment] 2015-12-11 16:28
Hey hippojay, just wondering how the testing is going?

Keep up the good work
