### ISSUE TITLE
Incorrect Metadata with PleXBMC 3.4.5+ and Kodi 15.1 [Debian Stretch]

### ISSUE THREAD

**Issue by 13223qweesadk** [hippojay/plugin.video.plexbmc#133] opened 2015-10-24 16:20 UTC
Hello,

I've noticed that there seems to be an issue with PleXbmc parsing metadata correctly with any version of PleXBMC and Kodi 15.1 on Debian Stretch (tested on two different Debian machines using the same remote server).
Most of the data comes through alright, but various things are randomly incorrect.
The most notable is movie titles, but also some shows (no apparently pattern) air date, seasons, etc.
I've tested with this PleXBMC 3.4.5 and the betas, and it seems to be worse with the 4.0.0 betas (some of the data shows correctly with 3.4.5, a lot more is messed up with 4.0.0).
Don't recall if I tested with the older version of PleXBMC, but I'm pretty sure the issue is consistent.

I tested the same setup on a Windows machine (using the same remote server as the Debian ones) and had no issues with metadata, so I'm not sure why this issue is coming up in Debian.

Here are some examples:
http://cdn.glass-waltz.net/images/example1.jpg
http://cdn.glass-waltz.net/images/example2.jpg
[note for this example it's on episode 3 of season 3, but reads ep. 1 of season 1].

**Comment by Groggy** [comment] 2015-10-27 08:09
Hi,

I've got the exact same issue :
![Screenshot](https://www.dropbox.com/s/5paq1jhb3d0ipab/screenshot000.png?raw=1)

Here is the log generated when loading the same screen : https://gist.github.com/1582d3c04a59ff19a5f8.git

For some reason episode 9 and above have the right title (the 4 first episodes are masked).

I'm using Kodi 15.2 on Gentoo with Plex v0.9.12.17, PleXBMC 4.0.0 beta 4 and Amber skin 2.1.3 (from jester-xbmc repo).

**Comment by hippojay** [comment] 2015-10-27 08:23
@groggy the log file link just 404's. If debug+ is turned on in plexbmc log then it will give me the xml the items are created from and I should be able to see where the issue is.

**Comment by Groggy** [comment] 2015-10-27 08:36
Here is the working link : https://gist.github.com/Groggy/1582d3c04a59ff19a5f8

But I did not enable debug logging. I will do it tonight.

**Comment by Groggy** [comment] 2015-10-28 07:32
I updated the gist with debug+ logging enabled.

**Comment by hippojay** [comment] 2015-10-28 09:49
Thanks.  This is almost certainly a KODI issue.  PleXBMC is grabbing the correct data from Plex and passing it through to the KODI as can be seen in the log:

    NOTICE: PleXBMC -> addGUIItem : Adding Dir for [The Other Side]
    Passed details: {'rating': 7.6, 'aired': '2015-08-19', 'season': 2, 'tvshowtitle': 'Extant', 'sorttitle': 'Other Side', 'director': '', 'studio': '', 'year': 2015, 'genre': '', 'plot': 'Memories resurface as Molly succumbs to the virus; Julie is confronted with hard choices; and the Hybrids seek revenge.\n', 'episode': 9, 'title': 'The Other Side', 'mpaa': 'TV-14', 'writer': '', 'cast': [], 'tagline': '', 'playcount': 0}
    Passed extraData: {'fanart_image': 'http://192.168.1.101:32400/library/metadata/15274/art/1441969898 | X-Plex-Platform=KODI&X-Plex-Client-Platform=KODI&X-Plex-User=Groggy42&X-Plex-Device-Name=XXXXXXXXXX&X-Plex-Provides=player&X-Plex-Token=XXXXXXXXXXX&X-Plex-Model=unknown&X-Plex-Platform-Version=Linux/RPi&X-Plex-Client-Identifier=XXXXXXXXXXXX&X-Plex-Device=PleXBMC&X-Plex-Product=PleXBMC&X-Plex-Language=en&X-Plex-Version=4.0.0%7Ebeta4', 'VideoCodec': 'h264', 'resume': 0, 'ratingKey': '15442', 'mode': 5, 'key': '/library/metadata/15442', 'duration': 2360, 'banner': 'http://192.168.1.101:32400/library/metadata/15274/banner/1441969898', 'AudioCodec': 'ac3', 'xbmc_VideoCodec': 'h264', 'thumb': 'http://192.168.1.101:32400/photo/:/transcode?url=http%3A%2F%2Flocalhost%3A32400%2Flibrary%2Fmetadata%2F15442%2Fthumb%2F1441969898&width=720&height=720 | X-Plex-Platform=KODI&X-Plex-Client-Platform=KODI&X-Plex-User=Groggy42&X-Plex-Device-Name=XXXXX&X-Plex-Provides=player&X-Plex-Token=XXXXXXXXXXXX&X-Plex-Model=unknown&X-Plex-Platform-Version=Linux/RPi&X-Plex-Client-Identifier=XXXXXXXXXXXXXX&X-Plex-Device=PleXBMC&X-Plex-Product=PleXBMC&X-Plex-Language=en&X-Plex-Version=4.0.0%7Ebeta4', 'VideoResolution': '1080', 'xbmc_VideoAspect': '1.78', 'source': 'tvepisodes', 'xbmc_AudioCodec': 'ac3', 'AudioChannels': '6', 'VideoAspect': '1.78', 'xbmc_height': '1080', 'type': 'Video', 'xbmc_width': '1920', 'season_thumb': 'http://192.168.1.101:32400/library/metadata/15275/thumb/1441969898', 'xbmc_AudioChannels': '6'}

In this extract the show name is correct and the details being passed are correct.  The next step from here is to just plug them into the KODI listitem calls, which does not alter any data.

I'll try and get a debian client running in a vm, see if I can pull out any more information and open a big report with KODI for it.

**Comment by Groggy** [comment] 2015-10-28 20:09
I think you're right because I don't have the issue on OSMC or on OS X. There is something wrong with my build of Kodi.

**Comment by hippojay** [comment] 2015-11-13 23:27
Spent some time on this, and I think it's a KODI bug.  It looks to me like some sort of overflow issue in the listitem object that will pick up data from other fields when more than a few of the properties are populated.  I'll get it logged - although you usually have to provide a test addon to prove it.

**Comment by aramisathei** [comment] 2015-11-15 18:05
Just tested this with Kodi release 15.2~rc3+dfsg1-1~bpo8+1 (jessie-backports) and PleXBMC isengard-fixes on Debian Jessie [stable] and it worked without any metadata problems.
Not sure whether it's because of the isengard-fixes or jessie-backports using a different build of Kodi, but either way hope this helps.

**Comment by liebezeit** [comment] 2015-11-21 22:53
I was fine on Xubuntu 15.04+Kodi 15.2+PlexBMC 4.0.0beta4 but when I updated to Xubuntu 15.10 and had to reinstall Kodi I got this issue. Or perhaps it started when I upgraded to the latest PlexMediaServer around the same time, I'm not sure. Tried plexbmc-isengard-fixes but just got "ImportError: No module named plexserver" errors. Not sure what to do. Thanks for any help.

**Comment by hippojay** [comment] 2015-11-22 00:28
This is usually caused by .pyo/.pyc files being run ahead of the .py files.  This is normal, but pyo are only supposed to be run when the pyc are older. Mi'm wondering whether the move of modules has meant that .pyo are left behind, not recompiled and used ahead of the .py.

The best way is to either delete add on and reinstall - or go into the directory/folder and remove all .pyo/.pyc files yup can find.  Leave only the .py files behind.

**Comment by liebezeit** [comment] 2015-11-22 02:23
OK, I deleted some pyo files from the ~/.kodi/addons/plugin.video.plexbmc-isengard-fixes directory, and that seems to have fixed the one error. The .pyo files were recreated on next launch.

Now my plexbmc module is version 4.1.0 and the plexbmc helper is 3.4.2.

I'm still getting the bad metadata. Episode release dates are all set to "11/30/65535". Random (though perhaps fewer) titles are reduced to things like "0D", "0", or an integer followed by the last few characters of an episode title.

I'm not seeing anything in kodi.log that seems relevant. Let me know if I can provide any more details.

Thanks, liebezeit

**Comment by chrisjschultz** [comment] 2015-12-08 09:34
I have just installed plexbmc 4.0.0b4 on Xubuntu 15.10 with Kodi 15.2 and have the same issue.

**Comment by liebezeit** [comment] 2015-12-09 02:06
It's not a PlexBMC issue, as the same thing is happening with other add-ons. It's something to do with a change in Ubuntu 15.10.
http://trac.kodi.tv/ticket/16414
http://trac.kodi.tv/ticket/16421

**Comment by chrisjschultz** [comment] 2015-12-09 06:59
Thanks for that - saved me a couple of hours of digging :+1:

**Comment by klusark** [comment] 2015-12-19 20:37
I've got a fix for this
https://github.com/xbmc/xbmc/pull/8620

**Comment by jordanade** [comment] 2016-01-14 18:14
I installed Kodi 16 beta 5 and the problem seems to be fixed!

**Closed** 2022-04-08 15:57 UTC
