### ISSUE TITLE
Movie watched status

### ISSUE THREAD

**Issue by Baswazz** [hippojay/plugin.video.plexbmc#31] opened 2014-11-29 12:50 UTC
When i watch a movie completely, the status is 'On Deck' as i did not finish watching it.
This is on Raspberry Pi.

I am running:

Kodi build 25 november:
http://forum.kodi.tv/showthread.php?tid=176043&pid=1845723#pid1845723

**Comment by hippojay** [comment] 2015-03-11 15:23
Thanks - it because the addon doesn't immediately refresh the ondeck information.  once this happens the item disappears.

At the moment this is the expected behaviour.  I will look later at seeing if I can make this more up to date.

**Comment by hippojay** [comment] 2015-04-27 21:17
Closing this issue as I can see that on deck items are updated after watching a film/show, but the update can take a few seconds to complete.

**Closed by hippojay** 2015-04-27 21:17 UTC
