### ISSUE TITLE
UnicodeEncodeError when trying to launch PleXBMC

### ISSUE THREAD

**Issue by sintaxasn** [hippojay/plugin.video.plexbmc#44] opened 2015-03-06 16:12 UTC
Hey there,

I'm seeing the following error when I try to launch the latest Helix branch.

11:03:54 T:672   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u2019' in position 270: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\sintaxasn\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\default.py", line 4631, in <module>
                                                displaySections()
                                              File "C:\Users\sintaxasn\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\default.py", line 582, in displaySections
                                                plex_network.discover()
                                              File "C:\Users\sintaxasn\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plex.py", line 49, in discover
                                                self.discover_all_servers()
                                              File "C:\Users\sintaxasn\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plex.py", line 154, in discover_all_servers
                                                das_myplex = self.get_myplex_servers()
                                              File "C:\Users\sintaxasn\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plex.py", line 197, in get_myplex_servers
                                                xml = self.getMyPlexURL("/pms/servers")
                                              File "C:\Users\sintaxasn\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plex.py", line 262, in getMyPlexURL
                                                printDebug.debugplus(link)
                                              File "C:\Users\sintaxasn\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\common.py", line 36, in debugplus
                                                return self.dev(message)
                                              File "C:\Users\sintaxasn\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\common.py", line 33, in dev
                                                return self.__printDebug(message, 3)
                                              File "C:\Users\sintaxasn\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\common.py", line 40, in __printDebug
                                                print "%s%s -> %s : %s" % (self.main, self.sub, inspect.stack(0)[2][3], msg)
                                              File "<string>", line 7, in write
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 270: ordinal not in range(128)
                                            -->End of Python script error report<--
11:03:54 T:1328   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.plexbmc/?content_type=video
11:03:54 T:1328   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexbmc/?content_type=video) failed
11:03:54 T:14304  NOTICE: Thread BackgroundLoader start, auto delete: false

This is on a fresh install of Helix with no configuration except for myPlex username / password entered. Hope this helps.

Dan

**Comment by hippojay** [comment] 2015-03-06 16:42
Thanks. I'll get this fixed. 

Part of this rewrite is to limit the number of input points  so that these issues can be fixed for good - so your help is appreciated.

**Comment by hippojay** [comment] 2015-03-06 17:25
Ok - should be fixed now. Let me know how you get on

For info - the problem is that the requests' module I use for talking to the plex server is suppose to encode for me - but for some reason isn't.  So I've forced it now.

**Closed by hippojay** 2015-03-06 17:25 UTC

**Comment by sintaxasn** [comment] 2015-03-06 17:38
Works perfectly now. Thanks for the speedy fix! :)
