### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by Steph71** [hippojay/plugin.video.plexbmc#53] opened 2015-03-19 22:25 UTC
Hi,

I am trying to run the latest rev of the plugin on my kodi installation. 

I have uploaded  a debuglog. to:

http://xbmclogs.com/pvr42wwzv

Seems like the plugin can see my server. But then something goes wrong and plugin crashed.

Anyone an idea, what is going wong ?

Best Regards
Stephan

**Comment by hippojay** [comment] 2015-03-22 21:30
Not sure, and I'm not able to replicate.    What's happening is that it's taking more than 60 seconds to read all the data, so it raises an exception.  However for some reason the exception code itself causes an issue.

If I test for this and reduce the read timeout to 1 second (so it basically fails all the time) then I get the correct exception being raised and handled:

[code]
21:18:17 T:1497363520  NOTICE: PleXBMC -> getContent : URL suffix: all
21:18:17 T:1497363520  NOTICE: PleXBMC.plexserver -> processed_xml : We have been passed a full URL. Parsing out path
21:18:17 T:1497363520  NOTICE: PleXBMC.plexserver -> talk : URL is: /library/sections/1/all
21:18:18 T:1497363520  NOTICE: PleXBMC.plexserver -> talk : Server: read timeout for X.X.X.X on /library/sections/1/all
21:18:18 T:1497363520  NOTICE: PleXBMC.plexserver -> processed_xml : PARSE: it took 0.00 seconds to parse data from X.X.X.X
[/code]

This one might come down to something specific about your setup.

**Comment by hippojay** [comment] 2015-03-22 23:44
I've just uplited the version of the HTTP library (requests).  Could you give that a go and see if it makes any difference.

**Comment by hippojay** [comment] 2015-03-25 20:36
Ok - might have fixed this.  KODI has a version of the requests module, but this might not be at a high enough level to support the readtimeout.  I embed a version, but due to the python search order, it picks up the older version first.  I have altered the plugin to require a higher KODI version and tested it on my RPI2 to make sure it is imported correctly.  Hopefully this fixes the issue

**Comment by hippojay** [comment] 2015-03-26 14:53
I've had the fixed confirmed on the plex.tv forums - so I'm closing this issue.

**Closed by hippojay** 2015-03-26 14:53 UTC

**Comment by Steph71** [comment] 2015-03-26 20:37
Hi Hipppojay,

I can also confirm the fix. It caused me some trouble updateing to Kodi 14.1. Thereforr I did not resond that fast. Thanks for tracking down that issue !!!

Best Regards
Stephan
