### ISSUE TITLE
mode referenced before assignment

### ISSUE THREAD

**Issue by keyvanfatehi** [hippojay/plugin.video.plexbmc#128] opened 2015-09-20 04:45 UTC
```
04:43:55 T:1565512768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'mode' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 4120, in start_plexbmc
                                                amberskin()
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 2819, in amberskin
                                                WINDOW.setProperty("plexbmc.%d.year" % (sectionCount) , "ActivateWindow(%s,%s%s%s&mode=%s,return)" % (window, base_url, path, "/year", mode) )
                                            UnboundLocalError: local variable 'mode' referenced before assignment
                                            -->End of Python script error report<--
```

**Comment by keyvanfatehi** [comment] 2015-09-20 04:52
I was wondering why plexbmc was so bad but it turns out commenting out that one line made plexbmc able to finish loading all the stuff to make an amazing experience! In other words nothing plex-specific was really loading on my home screen i guess because this error would stop execution prior to loading all the plex-specific sections.

great work on this plugin -- unfortunately i dont know enough about the plugin or kodi's add on system to actually fix this error, so i'll wait patiently for the correct fix.

**Comment by hippojay** [comment] 2015-10-21 23:06
I'll close this as a duplicate of #103 .  I'll still fix it :-)

**Closed by hippojay** 2015-10-21 23:06 UTC
